filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/src/node-app/logs/*.log

output.elasticsearch:
  hosts: ["host.docker.internal:9200"]

setup.kibana:
  host: "host.docker.internal:5601"
